FROM node:22-alpine AS api_base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME/bin:$PATH"
RUN npm config set registry https://registry.npmmirror.com && \
    npm i -g pnpm@10.8.0 && \
    apk add --no-cache wait4x \
    --repository https://mirrors.aliyun.com/alpine/v3.20/main \
    --repository https://mirrors.aliyun.com/alpine/v3.20/community
COPY . /app
WORKDIR /app

FROM api_base as prod-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install

FROM api_base as builder
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install
RUN pnpm run build

FROM api_base as migrator

ENV DATABASE_HOST=""
ENV DATABASE_PORT=""
ENV DATABASE_USERNAME=""
ENV DATABASE_PASSWORD=""
ENV DATABASE_NAME=""

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm add @oxc-node/core

CMD ["sh", "./bash/migrator.sh"]

FROM api_base as seeder

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm add @oxc-node/core

ENV DATABASE_HOST=""
ENV DATABASE_PORT=""
ENV DATABASE_USERNAME=""
ENV DATABASE_PASSWORD=""
ENV DATABASE_NAME=""

CMD ["sh", "./bash/seeder.sh"]

FROM api_base as final

COPY --from=prod-deps /app/node_modules /app/node_modules
COPY --from=builder /app/dist /app/dist

EXPOSE 3000

VOLUME [ "/app/dist/config", "/app/dist/i18n" ]

CMD ["sh", "./bash/run.sh"]
