/* DO NOT EDIT, file generated by nestjs-i18n */

/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "exception": {
        "common": {
            "INTERNAL_ERROR": string;
        };
    };
    "validation": {
        "NOT_EMPTY": string;
        "IS_ARRAY": string;
        "NOT_EMPTY_HUMAN": string;
        "TYPE_ERROR": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
