/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "exception": {
        "common": {
            "INTERNAL_ERROR": string;
            "REJECT_REQUEST": string;
        };
        "permission": {
            "NOT_FOUND": string;
        };
        "menu": {
            "EXISTS": string;
            "NOT_FOUND": string;
        };
        "role": {
            "NOT_FOUND": string;
            "EXISTS": string;
        };
        "user": {
            "NOT_FOUND": string;
            "EXISTS": string;
            "PASSWORD_INCORRECT": string;
        };
    };
    "validation": {
        "NOT_EMPTY": string;
        "IS_ARRAY": string;
        "NOT_EMPTY_HUMAN": string;
        "TYPE_ERROR": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
