/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "exception": {
        "common": {
            "INTERNAL_ERROR": string;
            "FORBIDDEN": string;
        };
        "permission": {
            "NOT_FOUND": string;
        };
        "menu": {
            "EXISTS": string;
            "NOT_FOUND": string;
        };
        "role": {
            "NOT_FOUND": string;
            "EXISTS": string;
            "NOT_EMPTY": string;
        };
        "user": {
            "NOT_FOUND": string;
            "EXISTS": string;
            "PASSWORD_INCORRECT": string;
            "PASSWORD_NOT_MATCH": string;
        };
        "auth": {
            "INVALID_TOKEN": string;
            "TOKEN_EXPIRED": string;
            "SESSION_EXPIRED": string;
        };
        "preview": {
            "REJECT_THIS_REQUEST": string;
        };
        "lang": {
            "NOT_EXISTS": string;
            "EXISTS": string;
            "NOT_EXISTS_COMMON": string;
            "DELETE_LANG_CONFLICT": string;
        };
        "i18": {
            "EXISTS": string;
            "NOT_FOUND": string;
        };
    };
    "validation": {
        "NOT_EMPTY": string;
        "IS_ARRAY": string;
        "NOT_EMPTY_HUMAN": string;
        "TYPE_ERROR": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
