blank_issues_enabled: true
contact_links:
  - name: Questions or need help
    url: https://github.com/opentiny/tiny-pro/discussions
    about: Add this WeChat(opentiny-official, note on "tiny-pro"), we will invite you to the WeChat discussion group later.
