FROM node:22-alpine as base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME/bin:$PATH"
RUN npm config set registry https://registry.npmmirror.com && \
    npm i -g pnpm@10.8.0

COPY . /app
WORKDIR /app

FROM base as prod-deps
RUN pnpm uninstall @opentiny/vue-theme && \
    pnpm add @opentiny/vue-theme@3 && \
    pnpm install

FROM prod-deps as builder
RUN  pnpm run build

FROM nginx:alpine as final

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf.template /etc/nginx/conf.d/default.conf.template

ENV BACKEND_HOST = "";

CMD ["/bin/sh", "-c", "envsubst '${BACKEND_HOST}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
