name: Issue / Pull Request Auto Labeler

on:
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened, edited]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v4
